# Generated by Django 5.0.7 on 2024-08-01 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
