# Generated by Django 5.0.6 on 2024-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_channel_post_group_post_profile_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts_media'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
