# Generated by Django 5.0.7 on 2026-10-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_channel_post_group_post_profile_post_type_and_more'),
        ('profiles', '0002_alter_profile_banner_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='profiles.profile'),
        ),
    ]
