# Generated by Django 5.0.6 on 2024-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_friendship_unique_together'),
        ('requests', '0002_alter_friendrequest_accepted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
