# Generated by Django 5.0.7 on 2024-08-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_community_viewers'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewers',
            new_name='Viewer',
        ),
    ]
