# Generated by Django 5.0.7 on 2024-08-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_viewers_viewer'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'group')},
        ),
    ]
